<!DOCTYPE Driver [
    <!ELEMENT Driver (Driver_Registration*)>
    <!ELEMENT Driver_Registration (name, contactInfo, age)>
    <!ATTLIST Driver_Registration ID CDATA #REQUIRED>
    <!ATTLIST Driver_Registration isVerified (Y|N) #REQUIRED>
    <!ATTLIST Driver_Registration gender (M|F|other) #IMPLIED>

    
    <!ELEMENT name (title?, firstname, surname)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT surname (#PCDATA)>

    <!ELEMENT contactInfo (PhoneNo, email)>
    <!ELEMENT PhoneNo (#PCDATA)>
    <!ELEMENT email (#PCDATA)>

    <!ELEMENT age (#PCDATA)>
]>

<Driver>
    <Driver_Registration ID="22337295" isVerified="Y">
        <name>
            <title>Mr</title>
            <firstname>John</firstname>
            <surname>Smith</surname>
        </name>
        <contactInfo>
            <PhoneNo>875635573</PhoneNo>
            <email>jsmith@gmail.com</email>
        </contactInfo>
        <age>33</age>
    </Driver_Registration>
    <Driver_Registration ID="82361623" isVerified="Y">
        <name>
            <title>Mrs</title>
            <firstname>Mary</firstname>
            <surname>Patterson</surname>
        </name>
        <contactInfo>
            <PhoneNo>852735288</PhoneNo>
            <email>mpatt21@gmail.com</email>
        </contactInfo>
        <age>54</age>
    </Driver_Registration>
    <Driver_Registration ID="2381232" isVerified="Y">
        <name>
            <title>Mr</title>
            <firstname>Gary</firstname>
            <surname>Murphy</surname>
        </name>
        <contactInfo>
            <PhoneNo>0912316252</PhoneNo>
            <email>thegmurph@gmail.com</email>
        </contactInfo>
        <age>26</age>
    </Driver_Registration>
</Driver>