<?xml version="1.0"?>
<!DOCTYPE rentalCenterDB [
<!ELEMENT rentalCenterDB (rentalCenter*)>
<!ELEMENT rentalCenter (full, workingTime, email, Stock, Address)>

<!ELEMENT full (#PCDATA)>

<!ELEMENT workingTime (openingTime, closingTime)>
<!ELEMENT openingTime (hour, minute)>
<!ELEMENT closingTime (hour, minute)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT minute (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!ELEMENT Stock (capacity, spaceLeft)>
<!ELEMENT capacity (#PCDATA)>
<!ELEMENT spaceLeft (#PCDATA)>

<!ELEMENT Address (street, city, county?, country, postalCode)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT county (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postalCode (#PCDATA)>

<!ATTLIST rentalCenter id CDATA #REQUIRED>
]>

<rentalCenterDB>
    <rentalCenter id="BaggotStreet">
        <full>False</full>
        <workingTime>
            <openingTime>
                <hour>8</hour>
                <minute>30</minute>
            </openingTime>
            <closingTime>
                <hour>19</hour>
                <minute>30</minute>
            </closingTime>
        </workingTime>
        <email>baggotstreet@hertz.com</email>
        <Stock>
            <capacity>150</capacity>
            <spaceLeft>72</spaceLeft>
        </Stock>
        <Address>
            <street>2 Haddington Rd</street>
            <city>Dublin</city>
            <county>Dublin</county>
            <country>Ireland</country>
            <postalCode>D04YY05</postalCode>
        </Address>
    </rentalCenter>
    <rentalCenter id="StPancras">
        <full>True</full>
        <workingTime>
            <openingTime>
                <hour>9</hour>
                <minute>00</minute>
            </openingTime>
            <closingTime>
                <hour>22</hour>
                <minute>30</minute>
            </closingTime>
        </workingTime>
        <email>stpancras@hertz.com</email>
        <Stock>
            <capacity>210</capacity>
            <spaceLeft>0</spaceLeft>
        </Stock>
        <Address>
            <street>St Pancras Way</street>
            <city>London</city>
            <country>England</country>
            <postalCode>N1C4QP</postalCode>
        </Address>
    </rentalCenter>
    <rentalCenter id="GareDuNord">
        <full>False</full>
        <workingTime>
            <openingTime>
                <hour>8</hour>
                <minute>00</minute>
            </openingTime>
            <closingTime>
                <hour>16</hour>
                <minute>00</minute>
            </closingTime>
        </workingTime>
        <email>garedunord@hertz.com</email>
        <Stock>
            <capacity>100</capacity>
            <spaceLeft>14</spaceLeft>
        </Stock>
        <Address>
            <street>112 Rue de Maubeuge</street>
            <city>Paris</city>
            <country>France</country>
            <postalCode>75010</postalCode>
        </Address>
    </rentalCenter>
    <rentalCenter id="CorkCity">
        <full>False</full>
        <workingTime>
            <openingTime>
                <hour>7</hour>
                <minute>45</minute>
            </openingTime>
            <closingTime>
                <hour>20</hour>
                <minute>15</minute>
            </closingTime>
        </workingTime>
        <email>corkcity@rental.ie</email>
        <Stock>
            <capacity>120</capacity>
            <spaceLeft>45</spaceLeft>
        </Stock>
        <Address>
            <street>1 South Mall</street>
            <city>Cork</city>
            <county>Cork</county>
            <country>Ireland</country>
            <postalCode>T12KX8D</postalCode>
        </Address>
    </rentalCenter>
    <rentalCenter id="LimerickCentral">
        <full>True</full>
        <workingTime>
            <openingTime>
                <hour>8</hour>
                <minute>00</minute>
            </openingTime>
            <closingTime>
                <hour>19</hour>
                <minute>00</minute>
            </closingTime>
        </workingTime>
        <email>limerickcentral@rental.ie</email>
        <Stock>
            <capacity>135</capacity>
            <spaceLeft>0</spaceLeft>
        </Stock>
        <Address>
            <street>52 O'Connell Street</street>
            <city>Limerick</city>
            <county>Limerick</county>
            <country>Ireland</country>
            <postalCode>V94E4X2</postalCode>
        </Address>
    </rentalCenter>
    <rentalCenter id="GalwayBay">
        <full>False</full>
        <workingTime>
            <openingTime>
                <hour>9</hour>
                <minute>30</minute>
            </openingTime>
            <closingTime>
                <hour>18</hour>
                <minute>45</minute>
            </closingTime>
        </workingTime>
        <email>galwaybay@rental.ie</email>
        <Stock>
            <capacity>110</capacity>
            <spaceLeft>65</spaceLeft>
        </Stock>
        <Address>
            <street>27 Eyre Square</street>
            <city>Galway</city>
            <county>Galway</county>
            <country>Ireland</country>
            <postalCode>H91T8NW</postalCode>
        </Address>
    </rentalCenter>
</rentalCenterDB>